root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
    dir = "."
    cmd = "go build -o ./tmp/main ./cmd/main.go"
    delay = 1000
    log = "build-errors.log"

[run]
    cmds = ["./tmp/main"]

[build.envs]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true